bool spawn_collision
bool use_mesh
string perception_service
string[] disabled_links
---
bool task_result
Object[] objects
string info # informational, e.g. for error messages.
---
string current_sub_task
builtin_interfaces/Time stamp
